version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test-publish-docker

jobs:
  build-test-publish-docker:
    docker:
      - image: circleci/openjdk:13.0.1-jdk-buster-node-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - bookit-event-{{ checksum "pom.xml" }}
            - bookit-event
      - run: mvn dependency:go-offline
      # Ensure it is possible to publish to ProTeamK60's repo on Docker hub
      - run: cp .mvn/wrapper/settings.xml ~/.m2/settings.xml
      - run: echo "<settingsSecurity><master>${maven_security_master}</master></settingsSecurity>" > ~/.m2/settings-security.xml
      - run: chmod +x ./mvnw
      - run:
          # Using Google Jib to build Docker image and publish it to Docker registry
          name: Build, unit test and install
          command: |
            ./mvnw install -B -P circleci \
              -Dbuild.number=${CIRCLE_BUILD_NUM} \
              -Dcommit.hash=${CIRCLE_SHA1} \
              -Dcircle.workflow.guid=${CIRCLE_WORKFLOW_ID} \
              -Dbuild.user=${CIRCLE_PROJECT_USERNAME} \
              -Dbuild.repo=${CIRCLE_PROJECT_REPONAME} 
      - save_cache:
          paths:
            - ~/.m2
          key: bookit-event-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports

